const firebaseConfig={
  apiKey:"AIzaSyB0LSbKdAAEfLg48c4DJO2hdyvjx0TySko",
  authDomain:"vm-radio-notifications.firebaseapp.com",
  projectId:"vm-radio-notifications",
  storageBucket:"vm-radio-notifications.firebasestorage.app",
  messagingSenderId:"573483400068",
  appId:"1:573483400068:web:5e3b80a9ac49dc284ebbd1",
  measurementId:"G-ZJPS49DKG3"
};
const VAPID_KEY="BPfmffszHy-sXlIEqIOJDTxPkC6-hn-4ThlFfZy9fgIp5DBxE_8XgqVzQLwIDnjlQv4phiUS_o8zfB9bjLGY3FY";
const NOTICE_KEY="vmRadioNotificationPromptShownV4";
const TOKEN_KEY="vmRadioFcmToken";
const ACTIVATED_KEY="vmRadioNotificationsActivatedV1";
const ERROR_KEY="vmRadioNotificationsLastErrorV1";
let welcomeObserver=null;
let messagingInstance=null;
let foregroundBound=false;

const style=document.createElement("style");
style.textContent=`
html.vm-notification-blocking #vmWelcomeSplash,body.vm-notification-blocking #vmWelcomeSplash{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
#vm-notification-overlay{position:fixed;inset:0;z-index:2147483647;background:rgba(0,0,0,.82);backdrop-filter:blur(5px);-webkit-backdrop-filter:blur(5px);display:flex;align-items:center;justify-content:center;padding:18px;box-sizing:border-box;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .25s ease,visibility .25s ease;font-family:Arial,Helvetica,sans-serif}
#vm-notification-overlay.vm-show{opacity:1;visibility:visible;pointer-events:auto}
#vm-notification-prompt{position:relative;width:min(100%,1360px);max-height:calc(100vh - 36px);overflow:auto;padding:54px 60px 52px;border:2px solid #b85cff;border-radius:34px;background:linear-gradient(145deg,#050308 0%,#0d0714 55%,#050308 100%);box-shadow:0 0 38px rgba(151,48,255,.55),inset 0 0 34px rgba(151,48,255,.07);color:#fff;box-sizing:border-box}
#vm-notification-prompt:before{content:"";position:absolute;inset:-2px;border-radius:34px;pointer-events:none;box-shadow:0 0 18px rgba(184,92,255,.9);opacity:.78}
#vm-notification-prompt .vm-notification-layout{display:grid;grid-template-columns:minmax(260px,34%) 1fr;gap:50px;align-items:center}
#vm-notification-prompt .vm-logo-placeholder{width:min(100%,200px);aspect-ratio:1;margin:auto;padding:8px;border:2px solid #9c3dff;border-radius:24px;display:flex;align-items:center;justify-content:center;background:radial-gradient(circle at 50% 45%,rgba(113,32,198,.14),rgba(0,0,0,.82) 72%);box-shadow:0 0 18px rgba(157,61,255,.36),inset 0 0 18px rgba(157,61,255,.08);overflow:hidden}
#vm-notification-prompt .vm-logo-placeholder img{display:block;width:100%;height:100%;object-fit:contain;object-position:center;border-radius:16px;filter:drop-shadow(0 0 10px rgba(170,75,255,.28))}
#vm-notification-prompt h2{margin:0;font-size:clamp(50px,5.6vw,92px);line-height:.98;font-weight:900;letter-spacing:-2px}
#vm-notification-prompt h2 span{color:#7e22ff;text-shadow:0 0 18px rgba(139,44,255,.55)}
#vm-notification-prompt .vm-line{height:3px;margin:30px 0 34px;background:linear-gradient(90deg,#8b2cff 0%,#8b2cff 48%,rgba(139,44,255,0) 100%);box-shadow:0 0 8px rgba(139,44,255,.6)}
#vm-notification-prompt .vm-text{margin:0;color:#d4ceda;font-size:clamp(22px,2vw,34px);line-height:1.42}
#vm-notification-prompt .vm-text span{color:#9c35ff}
#vm-notification-prompt .vm-notification-actions{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-top:44px;padding:0 10px}
#vm-notification-prompt button.vm-choice{border-radius:24px;padding:20px 24px;color:#fff;font-weight:800;font-size:clamp(22px,2vw,32px);cursor:pointer;min-height:100px;display:flex;align-items:center;justify-content:center;gap:22px}
#vm-notification-accept{border:0;background:linear-gradient(135deg,#c05cff 0%,#6d20ed 100%);box-shadow:0 0 28px rgba(145,45,255,.5)}
#vm-notification-later{background:rgba(5,3,9,.86);border:2px solid rgba(176,74,255,.58)}
#vm-notification-prompt button.vm-choice:disabled{opacity:.55;cursor:wait}
.vm-notification-icon-svg{width:42px;height:42px;display:block;flex:0 0 42px}
#vm-fcm-token-tool{position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:2147483646;width:min(92vw,520px);padding:16px 18px;border:2px solid #a43dff;border-radius:18px;background:rgba(8,4,15,.96);box-shadow:0 0 25px rgba(145,45,255,.55);color:#fff;font:700 16px Arial,sans-serif;text-align:center}
#vm-fcm-token-tool button{margin-top:10px;width:100%;border:0;border-radius:12px;padding:12px;background:linear-gradient(135deg,#c05cff,#6d20ed);color:#fff;font:800 16px Arial,sans-serif;cursor:pointer}
#vm-fcm-token-tool small{display:block;margin-top:8px;color:#cfc6d8;font-weight:400;line-height:1.35}
#vm-fcm-token-tool.vm-error{border-color:#ff5c9a;box-shadow:0 0 25px rgba(255,92,154,.3)}
#vm-fcm-token-tool.vm-error button{background:#32162d}
@media(max-width:800px){#vm-notification-overlay{padding:10px}#vm-notification-prompt{padding:30px 22px 26px;border-radius:26px;max-height:calc(100vh - 20px)}#vm-notification-prompt .vm-notification-layout{grid-template-columns:1fr;gap:16px}#vm-notification-prompt .vm-logo-placeholder{width:150px;max-width:150px;aspect-ratio:1;padding:6px;border-radius:20px}#vm-notification-prompt h2{font-size:clamp(38px,12vw,62px)}#vm-notification-prompt .vm-line{margin:18px 0 20px}#vm-notification-prompt .vm-text{font-size:clamp(17px,5vw,23px)}#vm-notification-prompt .vm-notification-actions{grid-template-columns:1fr 1fr;gap:10px;margin-top:28px;padding:0}#vm-notification-prompt button.vm-choice{min-height:68px;padding:12px 8px;border-radius:17px;font-size:clamp(15px,4vw,19px);gap:9px}.vm-notification-icon-svg{width:28px;height:28px;flex-basis:28px}}
`;
document.head.appendChild(style);

function markActivated(){localStorage.setItem(ACTIVATED_KEY,"1");localStorage.setItem(NOTICE_KEY,"1")}
function isActivated(){return localStorage.getItem(ACTIVATED_KEY)==="1"||localStorage.getItem(NOTICE_KEY)==="1"||(window.Notification&&Notification.permission==="granted")}
function lockWelcome(){document.documentElement.classList.add("vm-notification-blocking");document.body.classList.add("vm-notification-blocking");const hide=()=>{const el=document.getElementById("vmWelcomeSplash");if(el){el.style.setProperty("display","none","important");el.style.setProperty("visibility","hidden","important");el.style.setProperty("opacity","0","important");el.style.setProperty("pointer-events","none","important")}};hide();if(welcomeObserver)welcomeObserver.disconnect();welcomeObserver=new MutationObserver(hide);welcomeObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:["style","class"]})}
function unlockWelcome(){if(welcomeObserver){welcomeObserver.disconnect();welcomeObserver=null}document.documentElement.classList.remove("vm-notification-blocking");document.body.classList.remove("vm-notification-blocking");const el=document.getElementById("vmWelcomeSplash");if(el){el.style.removeProperty("display");el.style.removeProperty("visibility");el.style.removeProperty("opacity");el.style.removeProperty("pointer-events");el.classList.remove("vmWelcomeHide")}}
const clockIcon=`<svg class="vm-notification-icon-svg" viewBox="0 0 64 64" fill="none"><circle cx="32" cy="32" r="25" stroke="currentColor" stroke-width="4"/><path d="M32 17v16l10 7" stroke="currentColor" stroke-width="4" stroke-linecap="round"/></svg>`;
const bellIcon=`<svg class="vm-notification-icon-svg" viewBox="0 0 64 64" fill="none"><path d="M18 28c0-9 6-15 14-15s14 6 14 15v10l6 8H12l6-8V28Z" stroke="currentColor" stroke-width="4"/><path d="M26 51c1 4 3 6 6 6s5-2 6-6" stroke="currentColor" stroke-width="4" stroke-linecap="round"/></svg>`;
function createPrompt(){let overlay=document.getElementById("vm-notification-overlay");if(overlay)return overlay;overlay=document.createElement("div");overlay.id="vm-notification-overlay";overlay.innerHTML=`<section id="vm-notification-prompt" role="dialog" aria-modal="true" aria-label="Notifications VM RADIO"><div class="vm-notification-layout"><div class="vm-logo-placeholder"><img src="./vmradio-app-logo.png?v=15" alt="VM RADIO"></div><div><h2>Restez<br><span>informé</span> !</h2><div class="vm-line"></div><p class="vm-text">Activez les notifications pour ne rien manquer de nos <span>nouveautés</span>, <span>informations</span> et <span>mises à jour</span> sur <span>VM Radio</span>.</p></div></div><div class="vm-notification-actions"><button class="vm-choice" id="vm-notification-later" type="button">${clockIcon}<span>Plus tard</span></button><button class="vm-choice" id="vm-notification-accept" type="button">${bellIcon}<span>Activer</span></button></div></section>`;document.body.appendChild(overlay);return overlay}
function closePrompt(){const overlay=document.getElementById("vm-notification-overlay");if(!overlay)return;overlay.classList.remove("vm-show");setTimeout(()=>overlay.remove(),250)}
function finishPrompt(){closePrompt();setTimeout(unlockWelcome,350)}
function chooseLater(){finishPrompt()}
function showTokenTool(token,errorMessage){const old=document.getElementById("vm-fcm-token-tool");if(old)old.remove();const box=document.createElement("div");box.id="vm-fcm-token-tool";if(token){box.innerHTML=`<div>✅ Notifications activées</div><small>Le token FCM de cet appareil est prêt pour le test Firebase.</small><button type="button" id="vm-copy-fcm-token">Copier mon token FCM</button>`}else{box.classList.add("vm-error");const safeError=String(errorMessage||"Erreur inconnue").replace(/[<>]/g,"");box.innerHTML=`<div>⚠️ Notifications activées, mais token FCM indisponible</div><small>${safeError}<br>Ouvre la console du navigateur pour voir l'erreur complète.</small><button type="button" id="vm-close-fcm-error">Fermer</button>`}document.body.appendChild(box);const btn=box.querySelector("#vm-copy-fcm-token");if(btn)btn.onclick=async()=>{try{await navigator.clipboard.writeText(token);btn.textContent="Token copié ✅";setTimeout(()=>box.remove(),1200)}catch(error){btn.textContent="Copie impossible — token dans la console";console.log("VM RADIO FCM TOKEN:",token)}};const close=box.querySelector("#vm-close-fcm-error");if(close)close.onclick=()=>box.remove()}
async function setupMessaging(){if(messagingInstance)return messagingInstance;if(!(window.Notification)&&!("serviceWorker" in navigator))throw new Error("Notifications indisponibles");const [{initializeApp},{getMessaging,getToken,onMessage}]=await Promise.all([import("https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js"),import("https://www.gstatic.com/firebasejs/12.17.1/firebase-messaging.js")]);const app=initializeApp(firebaseConfig,"vmRadioNotifications");const messaging=getMessaging(app);const registration=await navigator.serviceWorker.register("./sw.js?vm=16",{scope:"./"});const token=await getToken(messaging,{vapidKey:VAPID_KEY,serviceWorkerRegistration:registration});if(!token)throw new Error("Token FCM indisponible");localStorage.setItem(TOKEN_KEY,token);localStorage.removeItem(ERROR_KEY);messagingInstance=messaging;if(!foregroundBound){onMessage(messaging,payload=>{const notification=payload.notification||{};const data=payload.data||{};const title=data.title||notification.title||"VM RADIO";const body=data.body||notification.body||"Une nouvelle information est disponible.";if(document.visibilityState==="visible"&&typeof Notification!=="undefined"&&Notification.permission==="granted"){try{new Notification(title,{body,icon:data.icon||notification.icon||"./vmradio-app-icon-192.png",tag:data.tag||"vm-radio",data:{url:data.url||"./"}})}catch(_){}}});foregroundBound=true}return messaging}
async function activateNotifications(btn){try{btn.disabled=true;btn.querySelector("span").textContent="Activation…";if(!(window.Notification)||!("serviceWorker" in navigator))throw new Error("Notifications non disponibles");const permission=await Notification.requestPermission();if(permission!=="granted"){finishPrompt();return}await setupMessaging();markActivated();finishPrompt();const token=localStorage.getItem(TOKEN_KEY);setTimeout(()=>showTokenTool(token,"Token FCM introuvable après activation."),450)}catch(error){console.error("VM RADIO notifications:",error);localStorage.setItem(ERROR_KEY,String(error&&error.message||error));finishPrompt();setTimeout(()=>showTokenTool(localStorage.getItem(TOKEN_KEY),String(error&&error.message||error)),450)}}
async function ensureMessagingWhenAlreadyGranted(){if(!(window.Notification)&&!("serviceWorker" in navigator))return;if(Notification.permission!=="granted")return;try{await setupMessaging();markActivated();const token=localStorage.getItem(TOKEN_KEY);setTimeout(()=>showTokenTool(token,"Token FCM introuvable après l'initialisation."),450)}catch(error){console.error("VM RADIO notifications init:",error);localStorage.setItem(ERROR_KEY,String(error&&error.message||error));showTokenTool(localStorage.getItem(TOKEN_KEY),String(error&&error.message||error))}}
function setupPrompt(){document.querySelectorAll("#vm-notifications-card").forEach(el=>el.remove());if(isActivated()){ensureMessagingWhenAlreadyGranted();return}lockWelcome();const overlay=createPrompt();requestAnimationFrame(()=>requestAnimationFrame(()=>{overlay.classList.add("vm-show");const accept=document.getElementById("vm-notification-accept");const later=document.getElementById("vm-notification-later");if(accept)accept.onclick=()=>activateNotifications(accept);if(later)later.onclick=chooseLater}))}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",setupPrompt,{once:true});else setupPrompt();
